#CREATE A NEW DATABASE
#CREATE A BOARD GAME TABLE
	#ID NAME PLAYER NUMBER LENGTH COST TIMES PLAYED
#CREATE A PLAYER TABLE
	#ID NAME, LAST NAME
#CREATE A SCORE TABLE
	#ID, DATE, GAME NUMBER, GAME, PLAYER, SCORE
#ADD A BOARD GAME TO THE LIST IF IT IS NOT ALREADY THERE
#ADD A PLAYER TO THE LIST IF IT IS NOT ALREADY THERE
#ADD A SCORE FOR A GAME
#REVIEW BOARD GAME TABLE
#REVIEW PLAYER TABLE
#REVIEW SCORE TABLE


